config { type: "table",
        name: "numeric_team_support",
        schema: "profitability",
        description: "Numeric team support. Building block for profitability.",
        tags: [
          "profitability",
          ],
        bigquery:{
          labels:{
            scheduler:"dataform",
            frequency:"daily",
            author:"Stakeholder"
          }
        },
        assertions: {
          },
        columns: {
          DATE: "The last day of the month for which the team support allocation is calculated.",
          demo_id: "The demo ID of the dealer.",
          entity_id: "The demo ID of the dealer converted to a string.",
          subsidiary_id: "The subsidiary ID, which is 6 for Demo Organization.",
          subsidiary_name: "The name of the subsidiary, which is 'Demo Organization'.",
          amount: "The allocated team support amount for the dealer.",
          impact_amount: "The allocated team support amount for the dealer.",
          account_type: "The account type, which is 'Income'.",
          account_number: "The account number for team support, which is '4110 - Team Support'.",
          item: "The financial type of the team support allocation.",
          description: "A description of the team support allocation, combining the vendor name and financial type.",
          vendor_id: "The vendor ID associated with the team support allocation.",
          distributor_id: "The distributor ID associated with the team support allocation.",
          program: "The program for which the team support is allocated, which is 'Team Support'.",
          category: "The category of the team support allocation.",
          business_segment: "The business segment for which the team support is allocated, which is 'Merchant'."
        }
}

  WITH
    sell_in AS (
      SELECT
        DATE,
        CASE
          WHEN demo_id IN (
            SELECT DISTINCT
              demo_id
            FROM
              `demo-project.demo_staging_netsuite.membership`
          ) THEN demo_id
          WHEN demo_id IS NULL THEN 0
          ELSE 0
        END AS demo_id,
        CASE
          WHEN vendor_id = 29
          AND brand_code = "SKS" THEN 9029
          WHEN vendor_id = 364
          AND brand_code = "JEN" THEN 9364
          WHEN vendor_id = 381
          AND brand_code = "MONOGRAM" THEN 9381
          WHEN vendor_id = 175 THEN 9175
          WHEN vendor_id IN (116, 152) THEN 1653
          ELSE vendor_id
        END AS vendor_id,
        distributor_id,
        SUM(
          CASE
            WHEN vendor_id = 175
            AND LOWER(IFNULL(source_file_brand, "")) != "bedding" THEN 0
            ELSE volume
          END
        ) AS volume
      FROM
        `demo-project.demo_reporting.sell_in`
      GROUP BY
        DATE,
        demo_id,
        vendor_id,
        distributor_id
    ),
    sell_in_adjustment AS (
      SELECT
        *,
        IFNULL(vendor_id, distributor_id) AS vendor_distributor
      FROM
        sell_in
    ),
    adjust_2 AS (
      SELECT
        DATE,
        demo_id,
        vendor_distributor,
        SUM(volume) AS volume
      FROM
        sell_in_adjustment
      GROUP BY
        DATE,
        demo_id,
        vendor_distributor
    ),
    gts AS (
      SELECT
        DATE,
        vendor_distributor,
        SUM(volume) AS grand_total
      FROM
        adjust_2
      GROUP BY
        DATE,
        vendor_distributor
    ),
    pcts AS (
      SELECT
        *,
        SAFE_DIVIDE(volume, grand_total) AS pct_of_total
      FROM
        adjust_2
        LEFT JOIN gts USING (DATE, vendor_distributor)
      WHERE
        grand_total != 0
    ),
    calendar AS (
      SELECT
        *
      FROM
        UNNEST (
          GENERATE_DATE_ARRAY(
            "2017-12-01",
            DATE_TRUNC(CURRENT_DATE(), MONTH),
            INTERVAL 1 MONTH
          )
        ) AS DATE
    ),
    vendor_calendar AS (
      SELECT
        *
      FROM
        calendar
        CROSS JOIN (
          SELECT DISTINCT
            vendor_distributor
          FROM
            pcts
        )
    ),
    reported AS (
      SELECT
        vendor_calendar.*,
        IF(
          vendor_reported.vendor_distributor IS NOT NULL,
          TRUE,
          FALSE
        ) AS has_reporting
      FROM
        vendor_calendar
        LEFT JOIN (
          SELECT DISTINCT
            DATE,
            vendor_distributor
          FROM
            pcts
        ) vendor_reported USING (DATE, vendor_distributor)
    ),
    prev_future_dates AS (
      SELECT
        curr.*,
        prev.date AS prev_date,
        IFNULL(prev.has_reporting, FALSE) AS prev_has_reporting,
        future.date AS future_date,
        future.has_reporting AS future_has_reporting
      FROM
        reported curr
        LEFT JOIN (
          SELECT
            *
          FROM
            reported
          WHERE
            has_reporting = TRUE
        ) prev ON curr.date > prev.date
        AND curr.vendor_distributor = prev.vendor_distributor
        LEFT JOIN (
          SELECT
            *
          FROM
            reported
          WHERE
            has_reporting = TRUE
        ) future ON curr.date < future.date
        AND curr.vendor_distributor = future.vendor_distributor
    ),
    prev_future_prefin AS (
      SELECT
        *,
        ROW_NUMBER() OVER (
          PARTITION BY
            DATE,
            vendor_distributor
          ORDER BY
            prev_date DESC
        ) prev_date_test,
        ROW_NUMBER() OVER (
          PARTITION BY
            DATE,
            vendor_distributor
          ORDER BY
            future_date ASC
        ) future_date_test
      FROM
        prev_future_dates
    ),
    takers AS (
      SELECT
        *,
        CASE
          WHEN has_reporting = TRUE THEN DATE
          WHEN has_reporting = FALSE
          AND prev_has_reporting = TRUE
          AND prev_date_test = 1 THEN prev_date
          WHEN has_reporting = FALSE
          AND prev_has_reporting = FALSE
          AND future_date_test = 1 THEN future_date
          ELSE NULL
        END AS take_this_date
      FROM
        prev_future_prefin
    ),
    bfill_ffill AS (
      SELECT DISTINCT
        DATE,
        vendor_distributor,
        has_reporting,
        take_this_date
      FROM
        takers
      WHERE
        take_this_date IS NOT NULL
    ),
    pct_allocations AS (
      SELECT
        bfill_ffill.date,
        bfill_ffill.vendor_distributor,
        pcts.demo_id,
        pct_of_total
      FROM
        bfill_ffill
        LEFT JOIN pcts ON pcts.date = bfill_ffill.take_this_date
        AND bfill_ffill.vendor_distributor = pcts.vendor_distributor
    ),
    ts AS (
      SELECT
        * EXCEPT (DATE, vendor_id),
        DATE(DATE) AS DATE,
        vendor_id AS vendor_distributor
      FROM
        `demo-project.demo_sources_tolga.team_support_netsuite_with_vendor_ids`
    ),
    test AS (
      SELECT
        *,
        team_support * pct_of_total AS team_support_allocation
      FROM
        ts
        LEFT JOIN pct_allocations USING (DATE, vendor_distributor) --where extract(year from date)=2023
    ),
    finalize AS (
      SELECT
        LAST_DAY(DATE, MONTH) AS DATE,
        demo_id,
        SAFE_CAST(demo_id AS STRING) AS entity_id,
        --null as linked_member_demo_id,
        --null as digital_customer_demo_id,
        6 AS subsidiary_id,
        "Demo Organization" AS subsidiary_name,
        team_support_allocation AS amount,
        team_support_allocation AS impact_amount,
        "Income" AS account_type,
        "4110 - Team Support" AS account_number, --might need to adjust account_number
        financial_type AS item,
        CONCAT(vendor_name, " - ", financial_type) AS description,
        CASE
          WHEN vendor_distributor IN (7, 86, 114, 97, 90, 94, 136, 96, 123) THEN NULL
          ELSE vendor_distributor
        END AS vendor_id, --might need to adjust query
        CASE
          WHEN vendor_distributor IN (7, 86, 114, 97, 90, 94, 136, 96, 123) THEN vendor_distributor
          ELSE NULL
        END AS distributor_id, --might need to adjust query
        "Team Support" AS program,
        class AS category,
        "Merchant" AS business_segment
      FROM
        test
      WHERE
        team_support_allocation != 0
    )
SELECT
*
FROM
finalize